spring.application.name=PerfermenceDemo

# ?????
spring.devtools.restart.enabled=true
# ?????????
spring.devtools.restart.additional-paths=src/main/java
# ??????????
spring.devtools.restart.exclude=static/**,public/**,WEB-INF/**

server.shutdown=graceful

# Kafka broker ?? (?? broker ???????)
spring.kafka.producer.bootstrap-servers=localhost:9092
# Producer ??
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# ???ack???all?????
spring.kafka.producer.acks=1

# ????
spring.kafka.producer.retries=2
