spring.application.name=PerfermenceDemo
spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.exclude=static/**,public/**,WEB-INF/**
server.shutdown=graceful
# Kafka broker
spring.kafka.producer.bootstrap-servers=localhost:9092
# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=1
spring.kafka.producer.retries=2

############H2 DB######################
# ?? H2 ???
spring.h2.console.enabled=true
# ?? H2 ?????
spring.h2.console.path=/h2-console
# ?????
spring.datasource.url=jdbc:h2:file:./temp/test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.sql.init.mode=always
# JPA ??
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none

############H2 DB######################
